# Generated by Django 2.1 on 2018-12-26 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('address', models.CharField(max_length=555, verbose_name='address')),
                ('city', models.CharField(max_length=555, verbose_name='city')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=255, verbose_name='image1')),
                ('image2', models.CharField(max_length=255, verbose_name='image2')),
                ('image3', models.CharField(max_length=255, verbose_name='image3')),
            ],
            options={
                'verbose_name': 'images',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardviews.Customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('inventory', models.CharField(max_length=255, verbose_name='inventory')),
                ('categorie', models.CharField(max_length=255, verbose_name='categorie')),
                ('section', models.CharField(max_length=255, verbose_name='section')),
                ('row', models.CharField(max_length=255, verbose_name='row')),
                ('link', models.CharField(max_length=470, verbose_name='link')),
                ('image', models.CharField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardviews.Images', verbose_name='images')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AlterUniqueTogether(
            name='images',
            unique_together={('image1', 'image2', 'image3')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('id', 'name', 'inventory', 'price', 'image', 'description', 'categorie', 'link', 'section', 'images', 'row')},
        ),
    ]
