# Generated by Django 2.1 on 2018-12-26 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardviews', '0002_auto_20181226_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanycharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'campany charge',
                'verbose_name_plural': 'campany charges',
            },
        ),
        migrations.CreateModel(
            name='Ownercharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'owner charge',
                'verbose_name_plural': 'owner charges',
            },
        ),
        migrations.CreateModel(
            name='Productcharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255, verbose_name='price')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'product charges',
                'verbose_name_plural': 'product charges',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AddField(
            model_name='productcharges',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardviews.Product', verbose_name='product'),
        ),
    ]
