# Generated by Django 2.1 on 2018-12-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardviews', '0003_auto_20181226_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharges',
            name='quantity',
            field=models.IntegerField(default=1, max_length=255, verbose_name='quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campanycharges',
            name='price',
            field=models.IntegerField(max_length=255, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(max_length=255, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ownercharges',
            name='price',
            field=models.IntegerField(max_length=255, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(max_length=255, verbose_name='inventory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=255, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='row',
            field=models.IntegerField(max_length=255, verbose_name='row'),
        ),
        migrations.AlterField(
            model_name='productcharges',
            name='price',
            field=models.IntegerField(max_length=255, verbose_name='price'),
        ),
    ]
