# Generated by Django 2.1 on 2018-12-26 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardviews', '0004_auto_20181226_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownercharges',
            name='owner',
        ),
        migrations.AddField(
            model_name='campanycharges',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcharges',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ownercharges',
        ),
    ]
