import React, { Component } from 'react';

class Terms extends Component {
  render() {
    return (
<div className="container container--tiny">
		<div className="section__title section__title--center">
            <h1 className="section__title-text h2">Terms and Conditions</h1>
        </div>

        <div className="page__content rte">
<div id="heading">
<p>Welcome to the thegreat-divide.com website terms and conditions for use. These terms and conditions apply to the use of this website at www.thegreat-divide.com . By accessing this website and/or placing an order, you agree to be bound by these terms and conditions.</p>
</div>
<p><span lang="EN-US">Using this website indicates that you accept these terms regardless of whether or not you choose to register with us or order from us. If you do not accept these terms, do not use this website.</span></p>
<p><b><span lang="EN-US">1.</span></b><span lang="EN-US"> Introduction</span></p>
<p><b><span lang="EN-US">1.1</span></b><span lang="EN-US"> You will be able to access most areas in thegreat-divide.com without registering your details with us. Certain areas of this Website are only open to you if you register.</span></p>
<p><b><span lang="EN-US">1.2</span></b><span lang="EN-US"> We may revise these terms and conditions at any time by updating this posting. You should check this Website from time to time to review the then current terms and conditions, because they are binding on you. Certain provisions of these terms and conditions may be superseded by expressly designated legal notices or terms located on particular pages of this Website. If you do not wish to accept any new terms and conditions after we have given notice, you should not continue to use this Website.</span></p>
<p><b><span lang="EN-US">2.</span></b><span lang="EN-US"> Ordering from thegreat-divide.com </span></p>
<p><b><span lang="EN-US">2.1 </span></b><span lang="EN-US">You are deemed to place an order with us by ordering via our online checkout process. As part of our checkout process you will be given the opportunity to check your order and to correct any errors. We will send you an order acknowledgement, detailing the products you have ordered.</span></p>
<p><b><span lang="EN-US">2.2 </span></b><span lang="EN-US">Our acceptance of an order takes place when we dispatch the order. We will send you a dispatch confirmation by email. When we dispatch the order the purchase contract will be made even if your payment has been processed immediately, unless we have notified you that we do not accept your order or you have cancelled your order.</span></p>
<p><b><span lang="EN-US">2.3 </span></b><span lang="EN-US">We may refuse to accept an order: (a) where goods are not available; (b) where we are unable to obtain authorisation for your payment; (c) if there has been a pricing or product description error; or (d) if you do not meet any eligibility criteria set out in our terms and conditions.</span></p>
<p><b><span lang="EN-US">3. </span></b><span lang="EN-US">Pricing</span></p>
<p><b><span lang="EN-US">3.1 </span></b><span lang="EN-US">All prices include VAT (where applicable) at the current rates. We reserve the right to express the price exclusive of VAT, but we shall show VAT separately and include it in the total price. We reserve the right to change the VAT rate as required by law.</span></p>
<p><b><span lang="EN-US">3.2 </span></b><span lang="EN-US">Where we charge separately for packing, postage and insurance and other relevant charges, the appropriate rates are set out in our specified pricing structure shown elsewhere on this Website.</span></p>
<p><b><span lang="EN-US">3.3 </span></b><span lang="EN-US">Our prices are reviewed periodically. Any prices shown on the website are current for the product at that time.</span></p>
<p><b><span lang="EN-US">4. </span></b><span lang="EN-US">Cancellation and Returns Policy</span></p>
<p><b><span lang="EN-US">4.1 </span></b><span lang="EN-US">If you wish to cancel your order: (a) You can notify us by email to joe@thegreat-divide.com before we have dispatched the goods to you; or (b) Where goods have already been dispatched to you, by returning goods to us in accordance with clause 4.2 below.</span></p>
<p><b><span lang="EN-US">4.2 </span></b><span lang="EN-US">You can return goods you have ordered from us for any reason at any time within 7 days of receipt for a full refund or exchange. The costs of returning goods to us shall be borne by you.</span></p>
<p><b><span lang="EN-US">4.3 </span></b><span lang="EN-US">Upon receipt of the goods we will give you a full refund of the amount paid or an exchange credit as required.</span></p>
<p><b><span lang="EN-US">4.4 </span></b><span lang="EN-US">The rights to return the goods to us as referred to in clause 4.3 will not apply in the following circumstances: - in the event that the product has been used or damaged by you in any way. The provisions of this clause 4.4 do not affect your statutory rights.</span></p>
<p><b><span lang="EN-US">5. </span></b><span lang="EN-US">Licence</span></p>
<p><b><span lang="EN-US">5.1 </span></b><span lang="EN-US">You are permitted to print and download extracts from this Website for your own use on the following basis: (a) no documents or related graphics on this Website are modified in any way; (b) no graphics on this Website are used separately from accompanying text; and (c) any of our copyright and trade mark notices and this permission notice appear in all copies.</span></p>
<p><b><span lang="EN-US">5.2 </span></b><span lang="EN-US">Unless otherwise stated, the copyright and other intellectual property rights in all material on this Website (including without limitation photographs and graphical images) are owned by us or our licensors. For the purposes of these terms and conditions, any use of extracts from this Website other than in accordance with clause 5.1 above for any purpose is prohibited. If you breach any of the terms in these terms and conditions, your permission to use this Website automatically terminates and you must immediately destroy any downloaded or printed extracts from this Website.</span></p>
<p><b><span lang="EN-US">5.3 </span></b><span lang="EN-US">Subject to clause 5.1, no part of this Website may be reproduced or stored in any other website or included in any public or private electronic retrieval system or service without our prior written permission.</span></p>
<p><b><span lang="EN-US">5.4 </span></b><span lang="EN-US">Any rights not expressly granted in these terms are reserved.</span></p>
<p><b><span lang="EN-US">6. </span></b><span lang="EN-US">Service Access</span></p>
<p><b><span lang="EN-US">6.1 </span></b><span lang="EN-US">While we endeavour to ensure that this Website is normally available 24 hours a day, we will not be liable if for any reason this Website is unavailable at any time or for any period.</span></p>
<p><b><span lang="EN-US">6.2 </span></b><span lang="EN-US">Access to this Website may be suspended temporarily and without notice in the case of system failure, maintenance or repair or for reasons beyond our control.</span></p>
<p><b><span lang="EN-US">7. </span></b><span lang="EN-US">Visitor Material and Conduct</span></p>
<p><b><span lang="EN-US">7.1 </span></b><span lang="EN-US">other than personally identifiable information, which is covered under the Privacy Policy, any material you transmit or post to this Website will be considered non-confidential and non-proprietary. We will have no obligations with respect to such material. We and our nominees will be free to copy, disclose, distribute, incorporate and otherwise use such material and all data, images, sounds, text and other things embodied therein for any and all commercial or non-commercial purposes</span></p>
<p><b><span lang="EN-US">7.2 </span></b><span lang="EN-US">You are prohibited from posting or transmitting to or from this Website any material: (a) that is threatening, defamatory, obscene, indecent, seditious, offensive, pornographic, abusive, liable to incite racial hatred, discriminatory, menacing, scandalous, inflammatory, blasphemous, in breach of confidence, in breach of privacy or which may cause annoyance or inconvenience; (b) for which you have not obtained all necessary licenses and/or approvals; (c) which constitutes or encourages conduct that would be considered a criminal offence, give rise to civil liability, or otherwise be contrary to the law of or infringe the rights of any third party, in the UK or any other country in the world; or (d) which is technically harmful (including, without limitation, computer viruses, logic bombs, Trojan horses, worms, harmful components, corrupted data or other malicious software or harmful data).</span></p>
<p><b><span lang="EN-US">7.3 </span></b><span lang="EN-US">You may not misuse the Website (including, without limitation, by hacking).</span></p>
<p><b><span lang="EN-US">7.4 </span></b><span lang="EN-US">We will fully co-operate with any law enforcement authorities or court order requesting or directing us to disclose the identity or locate anyone posting any material in breach of clauses 7.2 or 7.3.</span></p>
<p><b><span lang="EN-US">8. </span></b><span lang="EN-US">Links To and From Other Websites</span></p>
<p><b><span lang="EN-US">8.1 </span></b><span lang="EN-US">Links to third party websites on this Website are provided solely for your convenience. If you use these links, you leave this Website. We have not reviewed all of these third party websites and do not control and are not responsible for these websites or their content or availability. We therefore do not endorse or make any representations about them, or any material found there, or any results that may be obtained from using them. If you decide to access any of the third party websites linked to this Website, you do so entirely at your own risk. Use of any other website may be subject to terms and conditions applicable to such particular website.</span></p>
<p><b><span lang="EN-US">8.2 </span></b><span lang="EN-US">If you would like to link to this Website, you may only do so on the basis that you link to, but do not replicate, the home page of this Website, and subject to the following conditions: (a) you do not remove, distort or otherwise alter the size or appearance of the Great Divide logo; (b) you do not create a frame or any other browser or border environment around this Website; (c) you do not in any way imply that we are endorsing any products or services other than our own; (d) you do not misrepresent your relationship with us nor present any other false information about us; (e) you do not otherwise use any www.thegreatdivide.com trade marks displayed on this Website without our express written permission; (f) you do not link from a website that is not owned by you; and (g) your website does not contain content that is distasteful, offensive or controversial, infringes any intellectual property rights or other rights of any other person or otherwise does not comply with all applicable laws and regulations. We expressly reserve the right to revoke the right granted in this clause 8.2 for breach of these terms and to take any action we deem appropriate.</span></p>
<p><b><span lang="EN-US">8.3 </span></b><span lang="EN-US">You shall fully indemnify us for any loss or damage we may suffer or incur as a result of your breach of clause 8.2.</span></p>
<p><b><span lang="EN-US">9. </span></b><span lang="EN-US">Registration</span></p>
<p><b><span lang="EN-US">9.1 </span></b><span lang="EN-US">To register with thegreat-divide.com you must be over eighteen years of age.</span></p>
<p><b><span lang="EN-US">9.2 </span></b><span lang="EN-US">Each registration is for a single user only. We do not permit you to share your user name and password with any other person nor with multiple users on a network.</span></p>
<p><b><span lang="EN-US">9.3 </span></b><span lang="EN-US">Responsibility for the security of any passwords issued rests with you and if you know or suspect that someone else knows your password, you should contact us immediately.</span></p>
<p><b><span lang="EN-US">9.4 </span></b><span lang="EN-US">We may suspend or cancel your registration immediately at our reasonable discretion or if you breach any of your obligations under these terms and conditions.</span></p>
<p><b><span lang="EN-US">10. </span></b><span lang="EN-US">Disclaimer</span></p>
<p><b><span lang="EN-US">10.1 </span></b><span lang="EN-US">While we endeavour to ensure that the information on this Website is correct, we do not warrant the accuracy and completeness of the material on this Website. We may make changes to the material on this Website, or to the products and prices described in it, at any time without notice. The material on this Website may be out of date, and we make no commitment to update such material.</span></p>
<p><b><span lang="EN-US">10.2 </span></b><span lang="EN-US">The material on this Website is provided "as is" without any conditions, warranties or other terms of any kind. Accordingly, to the maximum extent permitted by law, we provide you with this Website on the basis that we exclude all representations, warranties, conditions and other terms (including, without limitation, the conditions implied by law of satisfactory quality, fitness for purpose and the use of reasonable care and skill) which but for these terms and conditions might have effect in relation to this Website.</span></p>
<p><b><span lang="EN-US">11.</span></b><span lang="EN-US"> Liability</span></p>
<p><b><span lang="EN-US">11.1 </span></b><span lang="EN-US">We, any other party (whether or not involved in creating, producing, maintaining or delivering this Website), and any of our group companies and the officers, directors, employees, shareholders or agents of any of them, exclude all liability and responsibility for any amount or kind of loss or damage that may result to you or a third party (including without limitation, any direct, indirect, punitive or consequential loss or damages, or any loss of income, profits, goodwill, data, contracts, use of money, or loss or damages arising from or connected in any way to business interruption, and whether in tort (including without limitation negligence), contract or otherwise) in connection with this Website in any way or in connection with the use, inability to use or the results of use of this Website, any websites linked to this Website or the material on such websites, including but not limited to loss or damage due to viruses that may infect your computer equipment, software, data or other property on account of your access to, use of, or browsing this Website or your downloading of any material from this Website or any websites linked to this Website.</span></p>
<p><b><span lang="EN-US">11.2 </span></b><span lang="EN-US">Nothing in these terms and conditions shall exclude or limit our liability for (i) death or personal injury caused by negligence (as such term is defined by the Unfair Contract Terms Act 1977); (ii) fraud; (iii) misrepresentation as to a fundamental matter; or (iv) any liability which cannot be excluded or limited under applicable law.</span></p>
<p><b><span lang="EN-US">11.3 </span></b><span lang="EN-US">If your use of material on this Website results in the need for servicing, repair or correction of equipment, software or data, you assume all costs thereof.</span></p>
<p><b><span lang="EN-US">11.4 </span></b><span lang="EN-US">You agree to indemnify us fully, defend and hold us, and our officers, directors, employees and agents, harmless from and against all claims, liability, damages, losses, costs (including reasonable legal fees) arising out of any breach of the terms and conditions by you, or your use of this Website, or the use by any other person using your registration details.</span></p>
<p><b><span lang="EN-US">12. </span></b><span lang="EN-US">Governing Law and Jurisdiction</span></p>
<p><b><span lang="EN-US">12.1 </span></b><span lang="EN-US">These terms and conditions shall be governed by and construed in accordance with English law. Disputes arising in connection with these terms and conditions shall be subject to the exclusive jurisdiction of the English courts.</span></p>
<p><b><span lang="EN-US">12.2 </span></b><span lang="EN-US">We do not warrant that materials/items for sale on the Website are appropriate or available for use outside the United Kingdom. It is prohibited to access the Website from territories where its contents are illegal or unlawful. If you access this Website from locations outside the United Kingdom, you do so at your own risk and you are responsible for compliance with local laws.</span></p>
<p><b><span lang="EN-US">13. </span></b><span lang="EN-US">Miscellaneous</span></p>
<p><b><span lang="EN-US">13.1 </span></b><span lang="EN-US">You may not assign, sub-license or otherwise transfer any of your rights under these terms and conditions</span></p>
<p><b><span lang="EN-US">13.2 </span></b><span lang="EN-US">If any provision of these terms and conditions is found by any court of competent jurisdiction to be invalid, the invalidity of that provision will not affect the validity of the remaining provisions which shall continue to have full force and effect.</span></p>
<p><b><span lang="EN-US">13.3 </span></b><span lang="EN-US">Only the parties to these terms and conditions may seek to enforce them under the Contracts (Rights of Third Parties) Act 1999.</span></p>
    	</div>
	</div>
    );
  }
}

export default Terms;
